#!/usr/bin/python
# -*- coding: utf-8 -*-

import unittest
from core.seo.audits.text.readability_text import ReadabilityText

class ReadabilityTest(unittest.TestCase):


    def test_01_textReadabilityScore_nocache(self):
        text = 'El interés que despierta la información de salud en Internet es obvio. Algunas pruebas de este interés están en el aumento de portales de salud con información para usuarios, así como, las numerosas páginas web de salud de distinto tipo: asociaciones de pacientes, organismos oficiales, páginas personales de pacientes y familiares afectados por determinadas dolencias. En la actualidad Internet facilita el acceso a cantidades incalculables de información. La presentación de la información relacionada con la salud en páginas web es cada vez más sofisticada, con avances manifiestos en la mejora de los contenidos, en la calidad y la fiabilidad de la información1-4 así como en la identificación de la autoría de los documentos. Pero al lado de estas mejoras se ponen sobre la mesa otros conceptos, como la «alfabetización en salud» (health literacy) y la legibilidad (readability) de los documentos de Internet, especialmente los dirigidos a los consumidores y población general.'
        text += 'El concepto de alfabetización en salud se utiliza por primera vez en el año 1974 en un informe de los Estados Unidos de Norteamérica acerca de la educación en salud como política social5. De las múltiples definiciones que surgen a partir de aquí nos quedamos con la que define la alfabetización como, «el grado por el cual los individuos tienen la capacidad de obtener, procesar y entender información básica de salud y los servicios que necesitan para tomar decisiones apropiadas en salud»6 .'
        text += 'La legibilidad o la relativa dificultad de descifrar las palabras7 es uno de los factores requeridos para que la información escrita sea fácilmente comprensible para lectores de cualquier nivel. En Estados Unidos los problemas de alfabetización en salud emergen desde el momento en el que paciente solicita información sobre sus problemas de salud y asume una responsabilidad en la toma de decisiones sobre su estado de salud. En el mundo anglosajón el concepto está relacionado directamente con la educación en salud, la promoción de la salud y la prevención primaria.'
        text += 'Un análisis8 de la National Adult Literacy Survey de Estados Unidos de 1992 señala que alrededor de 90 millones de adultos americanos son analfabetos funcionales o marginalmente funcionales, teniendo dificultades para entender la información sobre los cuidados de salud que necesitan y reciben.'
        text += 'Un estudio realizado en dos hospitales públicos de Estados Unidos señala que el 31,5% de los pacientes de habla inglesa y el 61,7% de habla española presentan una inadecuada o marginal alfabetización funcional en salud9. Otro estudio presenta resultados semejantes en población anciana, es decir, el 33,9% de los angloparlantes y el 53,9 de los pacientes de lengua española presentan una inadecuada o marginal alfabetización en salud10. Los análisis del Departamento de Salud de Canadá ponen de manifiesto que el 53% de los adultos mayores de 65 años tienen un nivel 1 de alfabetización en salud11, lo que supone que son incapaces de reconocer en los folletos de medicamentos la dosis de medicina para suministrar a un niño. Una de las indicaciones de este estudio es la necesidad de analizar las consecuencias de esta baja alfabetización. Otro estudio revela que la capacidad de lectura y comprensión de los pacientes presentan grandes diferencias, pero, en general, es inferior al nivel de escolarización que poseen12. En este sentido, el Departamento de Salud de los Estados Unidos recomienda que los documentos para la educación de las personas estén adaptados al nivel de lectura del 6.º grado. Para poder apreciar mejor el nivel de legibilidad recomendado, hay que tener en cuenta que la equivalencia de los estudios del sistema educativo de los Estados Unidos de América con los correspondientes españoles13 equipara el 8.º grado de USA a 2.º grado de la ESO, es decir, un nivel de lectura de un niño de 13 años.'
        text += 'Otro de los aspectos que reflejan indirectamente los conceptos de legibilidad y alfabetización en salud que estamos analizando, se ha puesto de manifiesto en estudios americanos que revelan el coste económico de la escasa o baja alfabetización en salud existente en USA14. Por ejemplo, estancias hospitalarias más altas debido a la falta de comprensión de los planes de tratamiento y a la toma inadecuada de medicación que, según el estudio, suponen un gasto adicional de 73 billones de $ en 1998. Además, se producen más visitas a los centros de salud y un mayor uso de los recursos hospitalarios especializados.'
        text += 'Existen más de 40 sistemas para medir la legibilidad de los textos15. Ninguno de ellos presenta una fórmula diseñada específicamente para textos médicos o relacionados con la salud7. Los modernos procesadores de textos ofrecen fórmulas para calcular la legibilidad, tales como: el nivel del grado de Flesch, la fórmula de la facilidad de la lectura de Flesch, el nivel de grado de Bormouth, el nivel de grado de Flesch-Kincaid. Otras fórmulas suponen el recuento manual, por ejemplo, la fórmula SMOG16 de legibilidad, y el Fry Readability Graph17. También está disponible software para realizar estas mediciones, por ejemplo, The Lexile FrameworkÒ y TextQuest. La literatura nos indica que si aplicamos las fórmulas mencionadas al mismo texto se producen resultados diferentes, se han llegado a encontrar variaciones de 1,3 a 3 niveles de grado entre diferentes programas18,19. El sistema que utilizan estas fórmulas es, en la mayoría de los casos, similar. Se seleccionan un número de frases de la primera parte del documento, el mismo número de frases de la mitad y la misma cantidad del final. Se contabilizan las sílabas de las palabras en cada grupo de frases, el número total de palabras contadas y se aplican las fórmulas oportunas. De todos los citados, el índice de Flesch-Kincaid se ha descrito como el más indicado para las instrucciones de autocuidados y para la información médica en general7. Flesch ideó esta fórmula para probar la legibilidad de los manuales de entrenamiento militar que, como las instrucciones de autocuidados y de información médica, han de ser comprensibles para adultos sometidos a tensión nerviosa y contienen, por necesidad, algún lenguaje técnico y términos poco corrientes. Kincaid ajustó la fórmula para obtener el nivel de lectura de un texto, adaptándose a un nivel de lectura de un instituto de los Estados Unidos.'
        text += 'El nivel de facilidad de lectura de Flesch (tabla 1) valora el texto en una escala de 100 puntos; cuanto más alto sea el resultado, más fácil será comprender el documento. Para la mayoría de los documentos estándar, el objetivo es un resultado comprendido entre 60 y 70 aproximadamente. La fórmula del nivel de facilidad de lectura de Flesch es: 206,835 – (1,015 ´ PLF) – (84,6 ´ PSP). Donde, PLF es el promedio de longitud de frase (el número de palabras dividido por el número de frases) y PSP el promedio de sílabas por palabra (el número de sílabas dividido por el número de palabras). El nivel de Flesch-Kincaid valora el texto en un nivel de instituto de los EE.UU. Por ejemplo, un resultado de 8,0 indica que puede comprender el documento un estudiante de octavo. Para la mayoría de los documentos, el objetivo es un resultado comprendido entre 7,0 y 8,0 aproximadamente.'
        language = 'es'
        readability = ReadabilityText(language)
        result = readability._textReadabilityScore(text)
        self.assertAlmostEqual(result, 70.0, None, "Readability: El texto ha obtenido una puntuación de: %d. Se esperaba 71.3", 5)


    def test_02_textReadabilityScore_cache(self):
        text = 'El interés que despierta la información de salud en Internet es obvio. Algunas pruebas de este interés están en el aumento de portales de salud con información para usuarios, así como, las numerosas páginas web de salud de distinto tipo: asociaciones de pacientes, organismos oficiales, páginas personales de pacientes y familiares afectados por determinadas dolencias. En la actualidad Internet facilita el acceso a cantidades incalculables de información. La presentación de la información relacionada con la salud en páginas web es cada vez más sofisticada, con avances manifiestos en la mejora de los contenidos, en la calidad y la fiabilidad de la información1-4 así como en la identificación de la autoría de los documentos. Pero al lado de estas mejoras se ponen sobre la mesa otros conceptos, como la «alfabetización en salud» (health literacy) y la legibilidad (readability) de los documentos de Internet, especialmente los dirigidos a los consumidores y población general.'
        text += 'El concepto de alfabetización en salud se utiliza por primera vez en el año 1974 en un informe de los Estados Unidos de Norteamérica acerca de la educación en salud como política social5. De las múltiples definiciones que surgen a partir de aquí nos quedamos con la que define la alfabetización como, «el grado por el cual los individuos tienen la capacidad de obtener, procesar y entender información básica de salud y los servicios que necesitan para tomar decisiones apropiadas en salud»6 .'
        text += 'La legibilidad o la relativa dificultad de descifrar las palabras7 es uno de los factores requeridos para que la información escrita sea fácilmente comprensible para lectores de cualquier nivel. En Estados Unidos los problemas de alfabetización en salud emergen desde el momento en el que paciente solicita información sobre sus problemas de salud y asume una responsabilidad en la toma de decisiones sobre su estado de salud. En el mundo anglosajón el concepto está relacionado directamente con la educación en salud, la promoción de la salud y la prevención primaria.'
        text += 'Un análisis8 de la National Adult Literacy Survey de Estados Unidos de 1992 señala que alrededor de 90 millones de adultos americanos son analfabetos funcionales o marginalmente funcionales, teniendo dificultades para entender la información sobre los cuidados de salud que necesitan y reciben.'
        text += 'Un estudio realizado en dos hospitales públicos de Estados Unidos señala que el 31,5% de los pacientes de habla inglesa y el 61,7% de habla española presentan una inadecuada o marginal alfabetización funcional en salud9. Otro estudio presenta resultados semejantes en población anciana, es decir, el 33,9% de los angloparlantes y el 53,9 de los pacientes de lengua española presentan una inadecuada o marginal alfabetización en salud10. Los análisis del Departamento de Salud de Canadá ponen de manifiesto que el 53% de los adultos mayores de 65 años tienen un nivel 1 de alfabetización en salud11, lo que supone que son incapaces de reconocer en los folletos de medicamentos la dosis de medicina para suministrar a un niño. Una de las indicaciones de este estudio es la necesidad de analizar las consecuencias de esta baja alfabetización. Otro estudio revela que la capacidad de lectura y comprensión de los pacientes presentan grandes diferencias, pero, en general, es inferior al nivel de escolarización que poseen12. En este sentido, el Departamento de Salud de los Estados Unidos recomienda que los documentos para la educación de las personas estén adaptados al nivel de lectura del 6.º grado. Para poder apreciar mejor el nivel de legibilidad recomendado, hay que tener en cuenta que la equivalencia de los estudios del sistema educativo de los Estados Unidos de América con los correspondientes españoles13 equipara el 8.º grado de USA a 2.º grado de la ESO, es decir, un nivel de lectura de un niño de 13 años.'
        text += 'Otro de los aspectos que reflejan indirectamente los conceptos de legibilidad y alfabetización en salud que estamos analizando, se ha puesto de manifiesto en estudios americanos que revelan el coste económico de la escasa o baja alfabetización en salud existente en USA14. Por ejemplo, estancias hospitalarias más altas debido a la falta de comprensión de los planes de tratamiento y a la toma inadecuada de medicación que, según el estudio, suponen un gasto adicional de 73 billones de $ en 1998. Además, se producen más visitas a los centros de salud y un mayor uso de los recursos hospitalarios especializados.'
        text += 'Existen más de 40 sistemas para medir la legibilidad de los textos15. Ninguno de ellos presenta una fórmula diseñada específicamente para textos médicos o relacionados con la salud7. Los modernos procesadores de textos ofrecen fórmulas para calcular la legibilidad, tales como: el nivel del grado de Flesch, la fórmula de la facilidad de la lectura de Flesch, el nivel de grado de Bormouth, el nivel de grado de Flesch-Kincaid. Otras fórmulas suponen el recuento manual, por ejemplo, la fórmula SMOG16 de legibilidad, y el Fry Readability Graph17. También está disponible software para realizar estas mediciones, por ejemplo, The Lexile FrameworkÒ y TextQuest. La literatura nos indica que si aplicamos las fórmulas mencionadas al mismo texto se producen resultados diferentes, se han llegado a encontrar variaciones de 1,3 a 3 niveles de grado entre diferentes programas18,19. El sistema que utilizan estas fórmulas es, en la mayoría de los casos, similar. Se seleccionan un número de frases de la primera parte del documento, el mismo número de frases de la mitad y la misma cantidad del final. Se contabilizan las sílabas de las palabras en cada grupo de frases, el número total de palabras contadas y se aplican las fórmulas oportunas. De todos los citados, el índice de Flesch-Kincaid se ha descrito como el más indicado para las instrucciones de autocuidados y para la información médica en general7. Flesch ideó esta fórmula para probar la legibilidad de los manuales de entrenamiento militar que, como las instrucciones de autocuidados y de información médica, han de ser comprensibles para adultos sometidos a tensión nerviosa y contienen, por necesidad, algún lenguaje técnico y términos poco corrientes. Kincaid ajustó la fórmula para obtener el nivel de lectura de un texto, adaptándose a un nivel de lectura de un instituto de los Estados Unidos.'
        text += 'El nivel de facilidad de lectura de Flesch (tabla 1) valora el texto en una escala de 100 puntos; cuanto más alto sea el resultado, más fácil será comprender el documento. Para la mayoría de los documentos estándar, el objetivo es un resultado comprendido entre 60 y 70 aproximadamente. La fórmula del nivel de facilidad de lectura de Flesch es: 206,835 – (1,015 ´ PLF) – (84,6 ´ PSP). Donde, PLF es el promedio de longitud de frase (el número de palabras dividido por el número de frases) y PSP el promedio de sílabas por palabra (el número de sílabas dividido por el número de palabras). El nivel de Flesch-Kincaid valora el texto en un nivel de instituto de los EE.UU. Por ejemplo, un resultado de 8,0 indica que puede comprender el documento un estudiante de octavo. Para la mayoría de los documentos, el objetivo es un resultado comprendido entre 7,0 y 8,0 aproximadamente.'
        language = 'es'
        readability = ReadabilityText(language)
        result = readability.textReadabilityScore(text)
        
        self.assertAlmostEqual(result, 70.0, None, "Readability: El texto ha obtenido una puntuación de: %d. Se esperaba 71.3", 5)
        
if __name__ == "__main__":
    unittest.main()
